# NB: this file was automatically generated by Dynare
#     from cournot.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(12, 22);
gp = zeros(12, 12, 22);
end
return (rp, gp)
end
